spring:
  sql:
    init:
      mode: always
      data-locations: classpath:db/local-data.sql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:shiftrhythm}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:shiftrhythm}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
